trigger:
- main

pool:
    vmImage: 'ubuntu-latest'

stages:
- stage: BuildApp
  jobs: 
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'MovieApp'
        repository: 'bestmoviesdb.azurecr.io'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.app'
        tags: '$(Build.BuildId)'

- stage: DeployDev
  jobs: 
   - job: DeployDev
     steps:
     

