trigger:
- main

pool:
    vmImage: 'ubuntu-latest'

stages:
- stage: BuildApp
  jobs: 
  - job: BuildPushImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'BestMoviesServiceConnection'
        repository: 'bestmovies.azurecr.io'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourceDirectory)/PresentationTier/Dockerfile'
        tags: '$(Build.BuildId)'