# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - newbestmoviesapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bestmovies.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9f58138b966149249cdc69d4e1acf057 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_427d3a12ccc54636acaabafcd605df2e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bestmovies.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9f58138b966149249cdc69d4e1acf057 }}/bestmoviesapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newbestmoviesapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8f677c835483464ab976029da3f3be1c }}
        images: 'bestmovies.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9f58138b966149249cdc69d4e1acf057 }}/bestmoviesapi:${{ github.sha }}'