# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - newbestmoviesapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bestmovies.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_951058ae21694fd49e9cf5ceda130d50 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aadabd5f41654c5f80ae0917c1f4abf4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bestmovies.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_951058ae21694fd49e9cf5ceda130d50 }}/bestmoviesapi:${{ github.sha }}
        file: ./Dockerfile.api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newbestmoviesapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_05c2f56a60b8488a95f3337042b93248 }}
        images: 'bestmovies.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_951058ae21694fd49e9cf5ceda130d50 }}/bestmoviesapi:${{ github.sha }}'
